# Generated by Django 2.1 on 2020-07-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie',
        ),
    ]
