# Generated by Django 2.1 on 2020-07-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.BooleanField(default=True),
        ),
    ]
