# Generated by Django 2.1 on 2020-07-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0002_movie_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='videoderby.Director'),
            preserve_default=False,
        ),
    ]
