# Generated by Django 2.1 on 2020-07-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0002_remove_movie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
