# Generated by Django 2.1 on 2020-08-02 11:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0003_remove_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no_photo.png', upload_to='videoderby/media/ActorPhotos')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='published',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoderby.Movie'),
        ),
    ]
