# Generated by Django 2.1 on 2020-08-02 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0005_auto_20200802_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
