# Generated by Django 2.1 on 2020-08-03 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0006_movie_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='compositor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
