# Generated by Django 2.1 on 2020-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0007_movie_compositor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
