# Generated by Django 2.1 on 2020-08-03 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0008_auto_20200803_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='compositor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
