# Generated by Django 2.1 on 2020-08-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoderby', '0009_auto_20200803_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery', to='videoderby.Movie'),
        ),
    ]
