# Generated by Django 2.1 on 2020-08-04 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoderby', '0011_auto_20200803_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_header', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=800)),
                ('rate', models.FloatField()),
                ('published', models.TimeField(auto_now=True)),
                ('total_likes', models.IntegerField()),
                ('total_dislikes', models.IntegerField()),
                ('addressed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videoderby.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=800)),
                ('published', models.TimeField(auto_now=True)),
                ('total_likes', models.IntegerField()),
                ('total_dislikes', models.IntegerField()),
                ('addressed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videoderby.Comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
